### ISSUE TITLE
{"error":"Required headers missing: x-hub-signature-256"}

### ISSUE THREAD

**Issue by jurajofsweden** [octokit/app.js#256]
We are using GitHub 2.22 which does not seem to send `x-hub-signature-256` in the webhook header, only `x-hub-signature`. 
This is causing an `{"error":"Required headers missing: x-hub-signature-256"}` when using the `@octokit/app` module.
Is there a way to tell the Octokit to use `x-hub-signature` instead of `x-hub-signature-256`  ?

**Comment by wolfy1339** [comment]
Unfortunately, there isn't any way to use `X-Hub-Signature` without editing the code.
The change was intentional, you can see here the comment on why: https://github.com/octokit/webhooks.js/pull/509#discussion_r603691104
At this point, I would say that GHES 2.22 isn't supported by `@octokit/webhooks` and thus `@octokit/app`

**Comment by jurajofsweden** [comment]
Thanks @wolfy1339 for a quick reply. I sort of understand the logic behind, but it unfortunately makes Octokit a bit less useful for us.

**Comment by gr2m** [comment]
The change was introduced in https://github.com/octokit/app.js/releases/tag/v12.0.0. You can use `@octokit/app@11`
